import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Aleo } from "next/font/google";
import "./globals.css";
import BaseProvider from "@/utils/providers/base-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const aleo = Aleo({ subsets: ["latin"], variable: "--font-aleo" });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aleo.variable} bg-background text-foreground`}
      >
        <BaseProvider>{children}</BaseProvider>
      </body>
    </html>
  );
}
